" Generated by vim-plug
" Sat Sep 10 22:42:14 2016
" :source this file in vim to restore the snapshot
" or execute: vim -S snapshot.vim

silent! let g:plugs['vim-airline'].commit = '65b9aa4'
silent! let g:plugs['vim-airline-themes'].commit = '020b843'

PlugUpdate!

